#!/bin/bash
export LC_NUMERIC=en_US.UTF-8	# Using . against ,
PLATFORM=0				#AMD PLATFORM
DEVICE=0				#SPECTRE == GPU
RESOLUTION=2500
REP=1
#MAX_THREADS=4
WORK_ITEMS_HW_LIMIT=256 # APUs HW limit for local_work_size per dimension
MAX_WORK_GROUP=8		# 8 GPU Cores ->  It's worthwhile testing bigger ??
STEP=0.01
mkdir results

for THREADS in 1 2 3 4
do
        mkdir ./results/$THREADS

        echo "Starting NUMTHREADS: $THREADS"
        w_items=4
		w_groups=1
		alpha=0.00
        while [ $((w_items*w_items)) -le $WORK_ITEMS_HW_LIMIT ]
        do
		echo "W_items: $w_items"
		w_groups=1
			while [ $w_groups -le $MAX_WORK_GROUP ]
			do
				echo "W_group: $w_groups"
				for alpha in $(seq 0.0 0.1 1.0)
				do
				#while [ $alpha -le 1.00 ]
				#do
			#	alpha=alpha|tr ',' '.'
                  ./bs -p $PLATFORM -d $DEVICE -t $THREADS -i $w_items -g $w_groups -a $alpha -n $RESOLUTION -r $REP >> ./results/$THREADS/$THREADS.txt
				echo "$alpha"
				done
				#alpha=$(alpha+STEP)
	            
				#done
			
            w_groups=$((w_groups+1))
			done
         w_items=$((w_items+1))
        done        
done
