#!/bin/bash
export LC_NUMERIC=en_US.UTF-8   # Using . against ,
APP=cedd
VIDEO=dame5
PLATFORM=0                              #AMD PLATFORM
DEVICE=0                                #SPECTRE == GPU
WORK_ITEMS_HW_LIMIT=256 # APUs HW limit for local_work_size per dimension
INPUT=input/$VIDEO/
OUTPUT=output/$VIDEO/
STEP=0.10
result2=0.00
REP=240
mkdir results

for THREADS in 1 2 3 4
do
        mkdir ./results/$THREADS

        echo "Starting NUMTHREADS: $THREADS"
        w_items=4
        alpha=0.00
        while [ $((w_items*w_items)) -le $WORK_ITEMS_HW_LIMIT ]
        do
                echo "W_items: $w_items"
                for alpha in $(seq 0.00 $STEP 1.00)
                do
#			if [ $alpa -eq 0.00 ] && [ $THREAD -ge 2 ]
			if [ "$(echo $alpha '==' $result2 | bc -l)" -eq 1 ] && [ $THREADS -ge 2 ]
			then
				echo "qqqqqqqqqq"
			else
				 ./$APP -p $PLATFORM -d $DEVICE -t $THREADS -i $w_items -a $alpha -f $INPUT -c $OUTPUT -r $REP >> ./results/$THREADS/$THREADS.txt
			fi
                echo "$alpha"
                done
         w_items=$((w_items+1))
        done
done

